# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user_list = [
    {username: "thisismyusername", first_name: "Ray", email: "email@gmail.com", password: "123"},
    {username: "dumbo43", first_name: "Troy", email: "gh@gmail.com", password: "123"},
    {username: "ihatebugz", first_name: "Carla", email: "tallkid@manh.com", password: "123"},
    {username: "moonbby", first_name: "Xavier", email: "wordsandwords@gmail.com", password: "123"},
    {username: "bofosho", first_name: "Minnie", email: "what@what.com", password: "123"},
    {username: "bangarang88", first_name: "Josh", email: "kackal@gmail.com", password: "123"},
    {username: "xXHauntedXx", first_name: "Jake", email: "gimmeavpn@gmail.com", password: "123"}
  ]
  
  question_list =[
    {text:"Which of the following bone is called collar bone?",
      first_answer: "Acetabulum",
      second_answer: "Pelvic Bone",
      third_answer: "Scapula",
      fourth_answer: "Clavicle",
      correct_answer: "Clavicle" },
    {text:"Glenoid cavity is found in __________",
      first_answer: "Pelvic girdle",
      second_answer: "Pectoral girdle",
      third_answer: "Sternum",
      fourth_answer: "Humerous",
      correct_answer: "Pectoral girdle" },
    {text:"Name of the shoulder bone is __________",
      first_answer: "Acetabulum",
      second_answer: "Pelvic bone",
      third_answer: "Scapula",
      fourth_answer: "Clavicle",
      correct_answer: "Scapula" },
    {text:"A Colles Fracture is associated with",
      first_answer: "Femur",
      second_answer: "Ulna",
      third_answer: "Radius",
      fourth_answer: "Humerous",
      correct_answer: "Radius" },
    {text:"Total number of bones found in the right upper limb is",
      first_answer: "25",
      second_answer: "26",
      third_answer: "30",
      fourth_answer: "60",
      correct_answer: "30" },
    {text:"An acromian process is characteristically found in _________",
      first_answer: "Pelvic girdle of mammals",
      second_answer: "Skull of frog",
      third_answer: "Pectoral girdle of mammals",
      fourth_answer: "Sperm of mammals",
      correct_answer: "Pectoral girdle of mammals" },
    {text:"Which cup lies at the junction of 3 bones of pelvic girdle?",
      first_answer: "Ilium",
      second_answer: "Ischium",
      third_answer: "Pubis",
      fourth_answer: "Acetabulum",
      correct_answer: "Acetabulum" },
    {text:"Which of the following is known as a knee cap?",
      first_answer: "Acetabulum",
      second_answer: "Tibia",
      third_answer: "Patella",
      fourth_answer: "Scapula",
      correct_answer: "Patella" },
    {text:"How many bones does ankle have?",
      first_answer: "8",
      second_answer: "9",
      third_answer: "6",
      fourth_answer: "7",
      correct_answer: "7" },
    {text:"Thumb (great toe) of foot is called _______",
      first_answer: "Pollex",
      second_answer: "Hallux",
      third_answer: "Index",
      fourth_answer: "Coracoid",
      correct_answer: "Hallux" },
    {text:"The total number of bones in lower extremity is ___________",
      first_answer: "62",
      second_answer: "63",
      third_answer: "61",
      fourth_answer: "60",
      correct_answer: "62" },
    {text:"Which of the following disease is associated with joints?",
      first_answer: "Gout",
      second_answer: "Osteoporosis",
      third_answer: "Arthritis",
      fourth_answer: "Tetany",
      correct_answer: "Arthritis" },
    {text:"Which cartilage is present at the joints of long bones?",
      first_answer: "Calcified",
      second_answer: "Elastic",
      third_answer: "Hyaline",
      fourth_answer: "Fibrous",
      correct_answer: "Hyaline" },
    {text:"Hinge joint is present between _______ and _______",
      first_answer: "Femur and ulna",
      second_answer: "Humerus and ulna",
      third_answer: "Femur and pectoral girdle",
      fourth_answer: "Femur and pelvic girdle",
      correct_answer: "Humerus and ulna" },
    {text:"How many ligaments are present in a wrist joint?",
      first_answer: "4",
      second_answer: "3",
      third_answer: "2",
      fourth_answer: "5",
      correct_answer: "4" },
    {text:"Joint with two articulations in one capsule medial side connects distal end of tibia and medial malleolus to talus. Lateral side connects malleolus of fibula with talus?",
      first_answer: "Talocrural joint",
      second_answer: "Lateral meniscus",
      third_answer: "Lateral ligament",
      fourth_answer: "Patellar ligament",
      correct_answer: "Talocrural joint" },
    {text:"Which blood cells secrete antibodies?",
      first_answer: "Eosinophils",
      second_answer: "Monocytes",
      third_answer: "Lymphocytes",
      fourth_answer: "Neutrophils",
      correct_answer: "Lymphocytes" },
    {text:"Absence of which clotting factor leads to Hemophilia-A?",
      first_answer: "Factor VII",
      second_answer: "Factor VIII",
      third_answer: "Factor IX",
      fourth_answer: "Factor X",
      correct_answer: "Factor VIII" },
    {text:"Which of the following is the thinnest blood vessel?",
      first_answer: "Artery",
      second_answer: "Arterioles",
      third_answer: "Meta Arterioles",
      fourth_answer: "Capillary",
      correct_answer: "Capillary" },
    {text:"How many compartments does thoracic cavity have?",
      first_answer: "3",
      second_answer: "2",
      third_answer: "1",
      fourth_answer: "4",
      correct_answer: "3" },
    {text:"What is the name of serous membrane that covers thoracic cavity?",
      first_answer: "Myocardium",
      second_answer: "Pericardium",
      third_answer: "Pleura",
      fourth_answer: "Lining membrane",
      correct_answer: "Pleura" }
  ]
  
  user_list.each do |u|
    User.create(u)
  end
  
  question_list.each do |q|
    question = User.first.questions.build(q)
    question.save
  end